# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.3

    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - add_ssh_keys:  # add key from CircleCI account based on fingerprint
          fingerprints:
            - "1a:04:31:46:6f:ba:12:d1:3f:5b:96:9c:83:47:3b:87"
            
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      - run:
          name: make html
          command: |
            . venv/bin/activate
            make html

      - deploy:
          command: |
            . venv/bin/activate
            ssh-add -D
            cp .circleci/deploy_key ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-add ~/.ssh/id_rsa
            git config user.email "yzmthu@163.com"
            git config user.name "Deployment Bot"
            git commit --allow-empty -m "Trigger deployment"
            ghp-import -p output 
            